// Post-build steps that need the finished dist/ directory.
//
//   1. sitemap.xml — the static pages plus one entry per community, fetched
//      from the live API so new communities show up without anyone editing a
//      file.
//   2. 404.html — a copy of index.html, which is how GitHub Pages serves a
//      client-routed SPA. Ignored by nginx, which uses try_files instead.
//
// Both write into dist/ rather than public/, so a build never leaves the
// working tree dirty.
//
// Run by `npm run build` and `npm run predeploy`. Overridable:
//   SITE_URL         canonical origin        (default https://propgather.com.my)
//   SITEMAP_API_URL  API base for projects   (default <SITE_URL>/api)
//   SITEMAP_SKIP=1   static pages only, no network

import { writeFile, copyFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DIST = path.join(ROOT, 'dist')

const SITE_URL = (process.env.SITE_URL || 'https://propgather.com.my').replace(/\/+$/, '')
const API_URL = (process.env.SITEMAP_API_URL || `${SITE_URL}/api`).replace(/\/+$/, '')
const FETCH_TIMEOUT_MS = 10_000

// Only pages worth a search result. /login, /my-communities and /admin are
// left out on purpose — they are `noindex` in src/seo.jsx, and a sitemap that
// lists noindex URLs just earns warnings in Search Console.
const STATIC_ROUTES = [
  { path: '/', changefreq: 'daily', priority: '1.0' },
  { path: '/discover', changefreq: 'daily', priority: '0.9' },
  { path: '/register', changefreq: 'monthly', priority: '0.8' },
  { path: '/contact', changefreq: 'yearly', priority: '0.5' },
  { path: '/privacy', changefreq: 'yearly', priority: '0.3' }
]

const xmlEscape = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;')

/**
 * Community pages are public even to signed-out visitors — they show the
 * project name and the "verified residents only" gate — so they are the long
 * tail worth indexing ("<condo name> residents forum").
 *
 * A build must never fail because the API is down or this is running offline,
 * so any failure degrades to the static routes and says so.
 */
async function fetchProjects() {
  if (process.env.SITEMAP_SKIP === '1') {
    console.log('[sitemap] SITEMAP_SKIP=1 — static pages only')
    return []
  }
  const url = `${API_URL}/projects`
  try {
    const res = await fetch(url, {
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      headers: { accept: 'application/json' }
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = await res.json()
    const projects = Array.isArray(data) ? data : (data?.items ?? [])
    if (!Array.isArray(projects)) throw new Error('unexpected response shape')
    console.log(`[sitemap] ${projects.length} communities from ${url}`)
    return projects
  } catch (err) {
    console.warn(`[sitemap] could not reach ${url} (${err.message}) — writing static pages only.`)
    console.warn('[sitemap] Set SITEMAP_API_URL, or SITEMAP_SKIP=1 to silence this.')
    return []
  }
}

function buildSitemap(projects, today) {
  const urls = [
    ...STATIC_ROUTES.map(r => ({ loc: `${SITE_URL}${r.path === '/' ? '/' : r.path}`, ...r })),
    ...projects
      .filter(p => p?.id != null)
      .map(p => ({
        loc: `${SITE_URL}/project/${encodeURIComponent(p.id)}`,
        changefreq: 'weekly',
        priority: '0.7',
        lastmod: p.updatedAt || p.createdAt
      }))
  ]

  const body = urls.map(u => {
    const lastmod = (u.lastmod ? String(u.lastmod).slice(0, 10) : today)
    return [
      '  <url>',
      `    <loc>${xmlEscape(u.loc)}</loc>`,
      `    <lastmod>${xmlEscape(lastmod)}</lastmod>`,
      `    <changefreq>${u.changefreq}</changefreq>`,
      `    <priority>${u.priority}</priority>`,
      '  </url>'
    ].join('\n')
  }).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/postbuild.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`
}

async function main() {
  if (!existsSync(DIST)) {
    console.error(`[postbuild] no dist/ at ${DIST} — run vite build first.`)
    process.exit(1)
  }

  const today = new Date().toISOString().slice(0, 10)
  const projects = await fetchProjects()
  const sitemap = buildSitemap(projects, today)
  await writeFile(path.join(DIST, 'sitemap.xml'), sitemap, 'utf8')
  console.log(`[sitemap] dist/sitemap.xml — ${STATIC_ROUTES.length + projects.length} URLs`)

  // GitHub Pages has no rewrite rule, so an unknown path serves 404.html. Vite
  // wrote absolute, base-aware asset URLs into index.html, so the same file
  // boots the app correctly from any depth and the router reads the real path.
  const indexHtml = path.join(DIST, 'index.html')
  await copyFile(indexHtml, path.join(DIST, '404.html'))
  // A soft 404 is only acceptable because the app renders its own NotFoundPage,
  // which is `noindex` — Google is told not to keep the URL either way.
  console.log('[postbuild] dist/404.html — SPA fallback for GitHub Pages')
}

main().catch(err => {
  console.error('[postbuild] failed:', err)
  process.exit(1)
})
